### PR TITLE
Bump to v0.6.0

### PR DESCRIPTION
**Pull request by xevisalle**

### CODE REVIEW

**Review by herr-seppia — APPROVED** [review]
LGTM, just a question

Why it is a major upgrade if you only add stuff?
If so it should be a minor, unless those "add" changed an implicit behaviour (that should be part of the changelog too)

**Comment by xevisalle** [comment]
> LGTM, just a question
> 
> Why it is a major upgrade if you only add stuff? If so it should be a minor, unless those "add" changed an implicit behaviour (that should be part of the changelog too)

it "adds" a check, but into an existing function. Will keep that in mind next time!

**Comment by herr-seppia** [comment]
> it "adds" a check, but into an existing function. Will keep that in mind next time!

In that case the entry should be "Change xxxx to perform additional check"

**Comment by xevisalle** [comment]
> > it "adds" a check, but into an existing function. Will keep that in mind next time!
> 
> In that case the entry should be "Change xxxx to perform additional check"

done!

**Pull request merged**
